Supported plugins.

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -118,4 +118,15 @@ if [ "${DATA_AVAILABLE}" != "0" ]; then
   fi
 fi
 
+#
+pushd "${OPENSHIFT_REPO_DIR}"
+RAILS_ENV=production rake redmine:plugins:migrate
+RET=$?
+popd
+
+if [ "${RET}" != "0" ]; then
+  echo "Failed to redmine:plugins:migrate with ${RET}" >&2
+  exit ${RET}
+fi
+
 exit 0
